version: "3.7"
services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
  redis:
    image: redis

volumes:
  mysql-data:
    name: tarpaulin-mysql-data
  minio-data:
    name: tarpaulin-minio-data
